name: Build UIBFF
on:
  # push:
  #   branches: [master]
  workflow_dispatch:
    inputs:
      imgPrefix:
        description: 'Image Prefix'
        required: false
        default: 'docker.io/sjjohn'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout-repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        id: setup-jdk
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Use Node.js ${{ matrix.node-version }}
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'

      - name: Check Node and NPM versions
        run: |
          node --version
          npm --version

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Setup Maven settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id": "github",
              "username": "${{ vars.SIRIUS_BUILD_GITHUB_USERNAME }}",
              "password": "${{ secrets.SIRIUS_BUILD_GITHUB_TOKEN }}"
            }]

      - name: Build with Maven
        run: mvn -e clean package
        env:
          GITHUB_USERNAME: ${{ vars.SIRIUS_BUILD_GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.SIRIUS_BUILD_GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-react-app
          path: target/*.jar

